### ISSUE TITLE
Feature: Add option to change settings via config file

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/beautyAmpCore2#2]
clone from https://github.com/sfm-cz/beautyAmpCore/issues/2

**************

in order to properly use the solution in a shared project folder one would want to be able to easily share the configuration in form of a (Json) file via git (examples from other tools: .eslintrc, .prettierrc, ...).
Your file should end on .json though to make editing them simple.

**Comment by FiB3** [comment]
Implemented the feature. Please, let me know if it works :)

**Comment by JoernBerkefeld** [comment]
hi @FiB3 could you please enhance the docs slidely on how you'd expect setup() to be called together if there is a config file?
also, can the `logs` param also exist in the config file or just `ampscript` and `editor`?

> **QUOTE:**
> A new experimental feature allows to use a setup file in your project's folder: .beautyamp.json:
```json
{
	"ampscript": {
		"capitalizeAndOrNot": true,
		"capitalizeIfFor": true,
		"capitalizeSet": true,
		"capitalizeVar": true,
		"maxParametersPerLine": 4
	},
	"editor": {
		"insertSpaces": true,
		"tabSize": 2
	}
}
```

**Comment by FiB3** [comment]
Hey @JoernBerkefeld,
In case you want to use the setup file (`.beautyamp.json`) you just need to include the file in root of your project. It should use it automatically. No extra work needed.
I won't be adding "logging" parameter in the file, as it's more for me.

"Experimental feature" - I have tested that and it seems to work on my side. :) But I haven't tested it extensively.

**Comment by JoernBerkefeld** [comment]
got it!
does that mean, that I can run setup() without params if I have that .beautyamp.json in my project root? That's not clear to me from the docs

**example:** 
```
beautifier.setup();
```

**Comment by JoernBerkefeld** [comment]
thank you

**Comment by FiB3** [comment]
@JoernBerkefeld What do you think about the improved README?

**Comment by JoernBerkefeld** [comment]
good!
i would suggest to improve it slightly though:

declare what happens if a config is found AND parameters are given to setup(). I am **assuming** that the values from the parameters supersede the config file but in the end that's up to how you wrote the code and hence should be mentioned explicitly.

something like...

```
Or create the config file `.beautyamp.json` in your project's folder (project root):
(...example code...)
You still need to call the `setup()` but you no longer need to supply parameters to it:
(...example code...)
If you want to override the config file's settings in some situations you can do so by calling `beautifier.setup(ampscript, editor);` with parameters like in the first example. This instance of beautifier will then use the code config while other instances will fall back to the config file's settings.
```

**Comment by FiB3** [comment]
Updated - I have added a line to readme.
